import { ClubEvent } from '../types';

export const CLUB_EVENTS: ClubEvent[] = [
  {
    id: 'event-1',
    title: 'Open Mic Night: Unplugged Vibes',
    shortDescription: 'An open stage for singers and musicians to perform live.',
    fullDescription: 'Join us for a soulful evening of live music performances. Whether you want to perform or just relax and enjoy, this event is designed to bring out the best musical talent on campus.',
    club: 'Music Club',
    eventType: 'Cultural',
    mode: 'offline',
    venue: 'College Auditorium',
    dateTime: '2026-04-18T18:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 192
  },
  {
    id: 'event-2',
    title: 'Street Dance Battle: Rhythm Clash',
    shortDescription: 'High-energy dance battle across multiple styles.',
    fullDescription: 'Compete with the best dancers in college and showcase your skills. Judges will evaluate based on creativity, timing, and energy.',
    club: 'Dance Club',
    eventType: 'Competition',
    mode: 'offline',
    venue: 'Open Air Stage',
    dateTime: '2026-04-22T17:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 270
  },
  {
    id: 'event-3',
    title: 'Drama Night: The Spotlight',
    shortDescription: 'Theatre performances from comedy to intense drama.',
    fullDescription: 'Experience powerful storytelling through live performances. Teams will present short plays judged on acting and direction.',
    club: 'Drama Club',
    eventType: 'Cultural',
    mode: 'offline',
    venue: 'Auditorium',
    dateTime: '2026-04-25T19:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 308
  },
  {
    id: 'event-4',
    title: 'AI Hackathon 2026',
    shortDescription: '24-hour hackathon to build AI-powered solutions.',
    fullDescription: 'Collaborate, build, and innovate using AI technologies. Teams will compete to solve real-world problems.',
    club: 'Tech Club',
    eventType: 'Hackathon',
    mode: 'hybrid',
    venue: 'Innovation Lab',
    dateTime: '2026-05-02T09:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 180
  },
  {
    id: 'event-5',
    title: 'Web3 & Blockchain Bootcamp',
    shortDescription: 'Hands-on session on smart contracts and dApps.',
    fullDescription: 'Learn blockchain fundamentals and build your first decentralized application using Solidity.',
    club: 'Tech Club',
    eventType: 'Workshop',
    mode: 'online',
    venue: 'Zoom Link',
    dateTime: '2026-04-12T16:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 220
  },
  {
    id: 'event-6',
    title: 'Photography Walk: Capture the Campus',
    shortDescription: 'Capture stunning campus moments with guided photography.',
    fullDescription: 'Explore the campus through a photographer’s lens. Learn composition, lighting, and storytelling.',
    club: 'Photography Club',
    eventType: 'Creative',
    mode: 'offline',
    venue: 'Campus Grounds',
    dateTime: '2026-04-15T06:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 100
  },
  {
    id: 'event-7',
    title: 'Startup Pitch Arena',
    shortDescription: 'Pitch your startup ideas to a panel of judges.',
    fullDescription: 'Present your business idea and receive feedback from experienced mentors and entrepreneurs.',
    club: 'Entrepreneurship Club',
    eventType: 'Competition',
    mode: 'offline',
    venue: 'Seminar Hall',
    dateTime: '2026-04-28T14:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 145
  },
  {
    id: 'event-8',
    title: 'Cybersecurity Basics Workshop',
    shortDescription: 'Learn ethical hacking fundamentals.',
    fullDescription: 'An introductory workshop covering cybersecurity basics, tools, and real-world scenarios.',
    club: 'Tech Club',
    eventType: 'Workshop',
    mode: 'online',
    venue: 'Google Meet',
    dateTime: '2026-03-20T10:00:00Z',
    status: 'past',
    isPublished: true,
    registrations: 300
  },
  {
    id: 'event-9',
    title: 'Tech Quiz Night',
    shortDescription: 'Fun and engaging tech trivia competition.',
    fullDescription: 'Test your knowledge in technology, coding, and general tech trends.',
    club: 'Tech Club',
    eventType: 'Fun Event',
    mode: 'offline',
    venue: 'Main Hall',
    dateTime: '2026-03-10T17:00:00Z',
    status: 'past',
    isPublished: true,
    registrations: 150
  },
  {
    id: 'event-10',
    title: 'Art & Sketch Jam',
    shortDescription: 'Express creativity through sketching and art.',
    fullDescription: 'A relaxing session where participants can create artwork, interact, and showcase creativity.',
    club: 'Art Club',
    eventType: 'Creative',
    mode: 'offline',
    venue: 'Art Room',
    dateTime: '2026-04-20T15:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 125
  },
  {
    id: 'event-13',
    title: 'Gaming Night: BGMI Showdown',
    shortDescription: 'Compete in intense BGMI matches and win prizes.',
    fullDescription: 'Join the ultimate battle royale! Compete in intense BGMI matches with teams, showcase your strategy, and win exciting prizes.',
    club: 'Gaming Club',
    eventType: 'Competition',
    mode: 'hybrid',
    venue: 'Gaming Zone & Discord',
    dateTime: '2026-04-30T20:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 320
  },
  {
    id: 'event-14',
    title: 'Poetry Slam: Voices Unleashed',
    shortDescription: 'Express your thoughts through poetry or just listen.',
    fullDescription: 'A platform for poets to share their soul through words. Whether you are a performer or an avid listener, come and be part of this lyrical journey.',
    club: 'Literary Club',
    eventType: 'Cultural',
    mode: 'offline',
    venue: 'College Garden',
    dateTime: '2026-04-19T17:30:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 140
  },
  {
    id: 'event-15',
    title: 'Robotics Build Session',
    shortDescription: 'Hands-on session to build and program basic robots.',
    fullDescription: 'Dive into the world of robotics! Learn to assemble hardware and write code to bring your robots to life in this hands-on workshop.',
    club: 'Robotics Club',
    eventType: 'Workshop',
    mode: 'offline',
    venue: 'Robotics Lab',
    dateTime: '2026-05-05T10:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 95
  },
  {
    id: 'event-16',
    title: 'Film Making Jam',
    shortDescription: 'Create short films with teams and showcase creativity.',
    fullDescription: 'Lights, camera, action! Form teams, script, shoot, and edit a short film in this high-energy creative marathon.',
    club: 'Media Club',
    eventType: 'Creative',
    mode: 'hybrid',
    venue: 'Media Studio',
    dateTime: '2026-04-26T11:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 110
  },
  {
    id: 'event-17',
    title: 'Fitness Challenge Week',
    shortDescription: 'Participate in daily fitness challenges and track progress.',
    fullDescription: 'Push your limits! Join a week-long fitness journey with daily challenges designed to test your endurance and strength.',
    club: 'Fitness Club',
    eventType: 'Challenge',
    mode: 'offline',
    venue: 'Campus Gym',
    dateTime: '2026-04-21T06:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 210
  },
  {
    id: 'event-18',
    title: 'Stand-Up Comedy Night',
    shortDescription: 'Laugh out loud with hilarious student performances.',
    fullDescription: 'Get ready for a night of non-stop laughter! Student comedians take the stage to share their best jokes and observations.',
    club: 'Drama Club',
    eventType: 'Cultural',
    mode: 'offline',
    venue: 'Auditorium Annex',
    dateTime: '2026-04-23T19:30:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 275
  },
  {
    id: 'event-19',
    title: 'Cloud Computing Seminar',
    shortDescription: 'Learn about AWS, cloud architecture, and deployment.',
    fullDescription: 'Explore the future of computing. This seminar covers cloud fundamentals, architecture patterns, and modern deployment strategies.',
    club: 'Tech Club',
    eventType: 'Talk',
    mode: 'online',
    venue: 'Webinar Link',
    dateTime: '2026-04-27T15:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 160
  },
  {
    id: 'event-20',
    title: 'Hack the Resume',
    shortDescription: 'Improve your resume with expert feedback.',
    fullDescription: 'Get your resume noticed! Join this workshop to learn how to highlight your skills and get personalized feedback from industry experts.',
    club: 'Placement Cell',
    eventType: 'Workshop',
    mode: 'online',
    venue: 'Zoom Meeting',
    dateTime: '2026-04-17T14:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 240
  },
  {
    id: 'event-21',
    title: 'Chess Tournament',
    shortDescription: 'Strategic chess competition for all skill levels.',
    fullDescription: 'Checkmate your opponents! A competitive tournament for chess enthusiasts, from beginners to grandmasters.',
    club: 'Chess Club',
    eventType: 'Competition',
    mode: 'hybrid',
    venue: 'Student Lounge & Lichess',
    dateTime: '2026-04-24T10:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 130
  },
  {
    id: 'event-22',
    title: 'Content Creation Bootcamp',
    shortDescription: 'Learn reels, editing, and social media growth strategies.',
    fullDescription: 'Master the art of content creation. Learn video editing, storytelling, and strategies to grow your personal brand on social media.',
    club: 'Media Club',
    eventType: 'Workshop',
    mode: 'online',
    venue: 'Live Stream',
    dateTime: '2026-04-29T16:00:00Z',
    status: 'upcoming',
    isPublished: true,
    registrations: 185
  }
];
